// Worker secrets, declared by hand.
//
// `cloudflare-env.d.ts` is regenerated by `pnpm cf-typegen`, which reads
// wrangler.jsonc — and secrets are deliberately not in that file. Declaring
// them there would be silently wiped on the next regen, so they live here and
// merge into the same interface.
//
// Set per environment with:
//   pnpm exec wrangler secret put <NAME> --env staging
//   pnpm exec wrangler secret put <NAME> --env production
// For local `wrangler dev` / `next dev`, put them in `.dev.vars`.
//
// Optional on purpose: the app must typecheck and build in CI, which has no
// secrets. Each read site is responsible for its own fallback or failure.

declare namespace Cloudflare {
  interface Env {
    /** HMAC salt for hashing visitor IPs before they reach D1. */
    TOOLS_IP_SALT?: string
    /** OpenRouter API key for the chatbot tool. Never sent to the client. */
    OPENROUTER_API_KEY?: string
    /** Set to 'true' to allow the paid model tier as a last-resort fallback. */
    OPENROUTER_ALLOW_PAID?: string
    /**
     * Raises the per-visitor daily crawl limit. Local development only —
     * localhost has no CF-Connecting-IP, so every request shares one counter
     * and three crawls exhausts the day. Leave unset in staging and production.
     */
    TOOLS_SESSIONS_PER_IP?: string
    /**
     * Transactional email provider key. Unset today, which makes
     * lib/tools/email.ts log verification codes instead of sending them.
     * Setting it also requires SPF and DKIM records on epyc.in.
     */
    RESEND_API_KEY?: string
    /**
     * Returns the verification code in the API response instead of only
     * logging it. **Staging only, while there is no email provider** — with it
     * set, verifying an address proves nothing, so anyone reaching the page can
     * claim an embed key. Only takes effect when `RESEND_API_KEY` is unset, so
     * configuring a provider disables it either way. Never set in production.
     */
    TOOLS_REVEAL_CODES?: string
  }
}
